### ISSUE TITLE
Help Understand Flow

### ISSUE THREAD

**Issue by bwright86** [cmroche/OctoPrint-HomeAssistant#10]
Hey there,

I am trying to understand the flow of this plugin a little better. Does it subscribe to the MQTT messages published by the MQTT plugin, or does it interrogate OctoPrint directly, and then publishes "Home Assistant" messages?

I am troubleshooting an issue on mine, where I discover my printer, and it has many sensors/binary_sensors, but no data is available from it.

## Versions
OctoPrint: v1.3.10 (v1.4.0 is available)
HomeAssistant: 1.0.1 (1.0.2 is available)
MQTT: 0.8.7

Note: I am currently upgrading to OctoPrint v1.4.0, so this may resolve some issues.

Here are some example messages being retained:
``` bash
~> $ mosquitto_sub -t homeassistant/# -v
homeassistant/binary_sensor/66FFEC_CONNECTED/config {"dev_cla": "connectivity", "json_attr_t": "~event/Connected", "stat_t": "~event/Connected", "device": {"mf": "Clifford Roche", "name": "OctoPrint", "mdl": "HomeAssistant Discovery for OctoPrint", "sw": "1.0.1", "ids": ["66FFEC"], "cns": [["mac", "b8:27:eb:xx:xx:xx"]]}, "pl_off": "Disconnected", "pl_on": "Connected", "pl_avail": "connected", "name": "OctoPrint Connected", "uniq_id": "66FFEC_CONNECTED", "pl_not_avail": "disconnected", "avty_t": "~mqtt", "~": "octoPrint/", "val_tpl": "{{value_json._event}}"}

homeassistant/sensor/66FFEC_TOOL0/config {"json_attr_t": "~temperature/tool0", "stat_t": "~temperature/tool0", "device": {"mf": "Clifford Roche", "name": "OctoPrint", "mdl": "HomeAssistant Discovery for OctoPrint", "sw": "1.0.1", "ids": ["66FFEC"], "cns": [["mac", "b8:27:eb:xx:xx:xx"]]}, "dev_cla": "temperature", "unit_of_meas": "\u00b0C", "pl_avail": "connected", "name": "OctoPrint Tool 0 Temperature", "uniq_id": "66FFEC_TOOL0", "pl_not_avail": "disconnected", "avty_t": "~mqtt", "~": "octoPrint/", "val_tpl": "{{value_json.actual|float}}"}
```

**Comment by cmroche** [comment]
OctoPrint-MQTT establishes and publishes updates to several messages. This plugin publishes additional topics which describe the format of data, and their interpretation for HomeAssistant so that it can register the device and sensors, following this process: https://www.home-assistant.io/docs/mqtt/discovery/

There is a topic octoPrint/mqtt which should contain either the status "connected" or "disconnected" which homeassistant watches to determine if OctoPrint is operational and the device is available. If you are seeing "unavailable" then check to make sure that topic is being updated correctly.

I'm making some assumption here though since I cannot see the issue. Could you show me the overview of the device please once OctoPrint is operational and idle (give it 2 minutes to complete status updates).

Also make sure you're on the latest, 1.1.3 as of this afternoon. Thank you.

**Comment by bwright86** [comment]
Sounds good, I will update once I’m on the latest version.

It sounds like this plugin does add new topics to MQTT. But I’m still unsure if the OctoPrint-MQTT is the data source, or if the OctoPrint system itself is the data source.

I do see that this Home Assistant plugin enriched the details. But I think when I update, it may become clearer.

Thank you for the response!

**Comment by cmroche** [comment]
The simple answer if that OctoPrint-MQTT provides the data, OctoPrint-HomeAssistant provides the device and entity definitions. The accurate answer is that it is complicated, the HA plugin does push advanced printer status data since I cannot rely on the MQTT plugin to either provide it, or update it at necessary intervals.

**Comment by bwright86** [comment]
Oh, how interesting...

So it sounds like the OctoPrint-MQTT plugin publishes the data, and the Home Assistant plugin publishes the discovery data?

Ultimately, this plugin is a pointer to the OctoPrint-MQTT, and it helps abstract the mapping. So once the discovery/mapping is done, it is up to the OctoPrint-MQTT plugin to publish messages that populate the discovered channels. Is that correct?

Thanks again for the responses, I have a lot to learn about OpenHAB and its plugins.
