### ISSUE TITLE
Is there a option to change fahrenheit to celsius?

### ISSUE THREAD

**Issue by 82280zx** [cmroche/OctoPrint-HomeAssistant#16]
I can't find where to change this =/ I See in your picture on the plugin page your using Celsius.

**Comment by cmroche** [comment]
You are seeing the temperature sensors in Home Assistant in Fehrenheit?

Actually this plugin only reports temperatures in celsius, I think nearly all printers are configured this way in their firmware. Do you happen to have your HA setup configured for F by default? HA will convert temperatures (correctly reporting the unit_of_measurment) to your HA system local. Check under `Configuration -> General -> Unit System` 

You could try creating a customization for that entity and override the unit_of_measurement property. Replace the `degree C` value with just `C`. This will cause HA to not understand the unit and so not convert it to your system local setting. I have not tried this, but it seems to be a common tactic in the home assistant forums.

**Comment by 82280zx** [comment]
I tried the override and no luck :( only way I've seen so far to change it is the Configuration -> General -> Unit System but that changes it everywhere :( I use both Celsius and Fahrenheit between all my things :(. Thank you for the great addon btw!

**Comment by cmroche** [comment]
Check the solution on this thread: https://community.home-assistant.io/t/override-system-wide-settings-for-temperature/193140/26 also first commented in this issue https://github.com/home-assistant/core/issues/24098

It looks like you should be able to use a template sensor to override the unit of measurement, but you'll need to provide the conversion function for the value_template.

There is further conversation about better supporting temperature unit overrides here https://github.com/home-assistant/architecture/issues/10

I'm going to close this issue since it is more specific to HA than this plugin. We can alway re-open again if you disagree.
