### ISSUE TITLE
Feature: Show printer firmware in device card

### ISSUE THREAD

**Issue by buffedelic** [cmroche/OctoPrint-HomeAssistant#57]
Would be nice if the device card in homeassistant show the firmware reported by the printer upon connection. 
I have a printer from Prusa and are not shure if this is specific to their product but I can imagine other do report firmware versions too.

For those with multiple printers, a MQTT message with the firmware might be handy to keep track of firmware versions across devices...

Terminal output:
```Recv: FIRMWARE_NAME:Prusa-Firmware 3.9.3 based on Marlin FIRMWARE_URL:https://github.com/prusa3d/Prusa-Firmware PROTOCOL_VERSION:1.0 MACHINE_TYPE:Prusa i3 MK3S EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000```

<img width="343" alt="Screenshot 2021-01-22 at 23 02 06" src="https://user-images.githubusercontent.com/10919597/105553541-dd108880-5d05-11eb-81f3-542af3c44017.png">

**Comment by cmroche** [comment]
@buffedelic Would you be willing to submit a merge request with this feature?

**Comment by buffedelic** [comment]
I already had a quick look and started working on it.
I will try to find some time to finnish it 👍

**Comment by cmroche** [comment]
I took a look into this today, and I think the change will be too problematic to make it work.

The issue has to do with the way that the MQTT integration (and probably all integrations) specify the firmware data at the time that the sensors are initialized, but in the case of OctoPrint, it's not possible to run the M115 command until the printer is connected, well after that initialization takes place. Due to this we won't be able to incorporate the M115 response in the device info.
