### ISSUE TITLE
Example card setup for Lovelace doesnt work

### ISSUE THREAD

**Issue by yasars** [cmroche/OctoPrint-HomeAssistant#74]
hi my friend can you check this exampe card for Lovelance!?

when you save your code , you can see it, when you go to edit you see it.... where is the bug :D

thx

![Bildschirmfoto 2021-09-01 um 15 57 23](https://user-images.githubusercontent.com/41986136/131684640-479ab2af-0a37-435b-9bf9-f1ec1e9d7d50.png)
![Bildschirmfoto 2021-09-01 um 15 57 26](https://user-images.githubusercontent.com/41986136/131684652-2e1dda77-03ff-4e96-b2de-32ce6a612e90.png)

**Comment by yasars** [comment]
can you look here and fix it 🗡️ 

`cards:
  - cards:
      - entity: sensor.ender_3_print_status
        name: Ender 3
        type: entity
        icon: None
      - entity: switch.ender3
        hold_action:
          action: more-info
        show_icon: true
        show_name: false
        tap_action:
          action: toggle
        type: button
    type: horizontal-stack
  - entities:
      - entity: automation.printer_ender_3_shutdown_when_cool
        name: Auto-shutdown when Cool
    show_header_toggle: false
    type: entities
mode: vertical
type: custom:stack-in-card
`

**Comment by cmroche** [comment]
There's a condition card in there which checks for availability of the printer, I think based on the switch that I am using. Lovelace auto-shows the cards when editing (since that makes sense).

I might look to change the example since technically the switch is an external component to this plugin, but the behaviour is as expected.
